var nombre; //declarar variable
nombre = "esta es una variable global"; //inicializar una variable y asigno un valor
var Nombre = "Hola mundo"; //declarar e inicializar

nombre = "Alexandra";
console.log(nombre);
nombre = "Diego";
console.log(nombre);
nombre = "Joaquin";
console.log(nombre);
nombre = "Gustavo";
console.log(nombre);
nombre = "Landia";
console.log(nombre);
nombre = "Mariana";

//La palabra reservada var y las varables que se creen con esta se pueden re declarar y re asignar
document.writeln(nombre);
console.log(nombre);

//Uso de et para declarar variables, no puede ser re definidas pero si re declaradas
let bebida = "Agua";
console.log(bebida);
bebida = "Gaseosa";
bebida = "jugo de naranja";
bebida = "Cerveza";
console.log(bebida);

//Uso del const
const orden = "Pasta italiana";
//Al ser defnida debe ser declarada al mismo tiempo, no puede ser re definidas ni re declaradas
console.log(orden);